
  import { defineConfig } from 'vite';
  import react from '@vitejs/plugin-react-swc';
  import path from 'path';

  export default defineConfig({
    plugins: [react()],
    resolve: {
      extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
      alias: {
        'vaul@1.1.2': 'vaul',
        'sonner@2.0.3': 'sonner',
        'recharts@2.15.2': 'recharts',
        'react-resizable-panels@2.1.7': 'react-resizable-panels',
        'react-hook-form@7.55.0': 'react-hook-form',
        'react-day-picker@8.10.1': 'react-day-picker',
        'next-themes@0.4.6': 'next-themes',
        'lucide-react@0.487.0': 'lucide-react',
        'input-otp@1.4.2': 'input-otp',
        'figma:asset/out_of_stock_label.png': path.resolve(__dirname, './src/assets/out_of_stock_label.png'),
        'figma:asset/lg_banner1.png': path.resolve(__dirname, './src/assets/lg_banner1.png'),
        'figma:asset/hisense1.png': path.resolve(__dirname, './src/assets/hisense1.png'),
        'figma:asset/hisense2.png': path.resolve(__dirname, './src/assets/hisense2.png'),
        'figma:asset/video.png': path.resolve(__dirname, './src/assets/video.png'),
        'figma:asset/maxi1.png': path.resolve(__dirname, './src/assets/maxi1.png'),
        'figma:asset/christmas_banner1.png': path.resolve(__dirname, './src/assets/christmas_banner1.png'),
        'figma:asset/actiu1.png': path.resolve(__dirname, './src/assets/actiu1.png'),
        'figma:asset/pylontech1.png': path.resolve(__dirname, './src/assets/pylontech1.png'),
        'figma:asset/growatt1.png': path.resolve(__dirname, './src/assets/growatt1.png'),
        'figma:asset/lg1.png': path.resolve(__dirname, './src/assets/lg1.png'),
        'figma:asset/lg2.png': path.resolve(__dirname, './src/assets/lg2.png'),
        'figma:asset/maxi2.png': path.resolve(__dirname, './src/assets/maxi2.png'),
        'figma:asset/maxi3.png': path.resolve(__dirname, './src/assets/maxi3.png'),
        'figma:asset/lg3.png': path.resolve(__dirname, './src/assets/lg3.png'),
        'figma:asset/hisense3.png': path.resolve(__dirname, './src/assets/hisense3.png'),
        'figma:asset/hisense4.png': path.resolve(__dirname, './src/assets/hisense4.png'),
        'figma:asset/lg4.png': path.resolve(__dirname, './src/assets/lg4.png'),
        'figma:asset/lg5.png': path.resolve(__dirname, './src/assets/lg5.png'),
        'figma:asset/huawei1.png': path.resolve(__dirname, './src/assets/huawei1.png'),
        'figma:asset/hisense5.png': path.resolve(__dirname, './src/assets/hisense5.png'),
        'figma:asset/hisense7.png': path.resolve(__dirname, './src/assets/hisense7.png'),
        'figma:asset/deye1.png': path.resolve(__dirname, './src/assets/deye1.png'),
        'figma:asset/hisense6.png': path.resolve(__dirname, './src/assets/hisense6.png'),
        'figma:asset/maxi4.png': path.resolve(__dirname, './src/assets/maxi4.png'),
        'figma:asset/appliances1.png': path.resolve(__dirname, './src/assets/appliances1.png'),
        'figma:asset/hisense8.png': path.resolve(__dirname, './src/assets/hisense8.png'),
        'figma:asset/refrigerator1.png': path.resolve(__dirname, './src/assets/refrigerator1.png'),
        'figma:asset/maxi6.png': path.resolve(__dirname, './src/assets/maxi6.png'),
        'figma:asset/deye2.png': path.resolve(__dirname, './src/assets/deye2.png'),
        'figma:asset/maxi5.png': path.resolve(__dirname, './src/assets/maxi5.png'),
        'figma:asset/audio1.png': path.resolve(__dirname, './src/assets/audio1.png'),
        'figma:asset/lg8.png': path.resolve(__dirname, './src/assets/lg8.png'),
        'figma:asset/huawei2.png': path.resolve(__dirname, './src/assets/huawei2.png'),
        'figma:asset/jinko.png': path.resolve(__dirname, './src/assets/jinko.png'),
        'figma:asset/huawei3.png': path.resolve(__dirname, './src/assets/huawei3.png'),
        'figma:asset/hisense11.png': path.resolve(__dirname, './src/assets/hisense11.png'),
        'figma:asset/huawei5.png': path.resolve(__dirname, './src/assets/huawei5.png'),
        'figma:asset/maxi8.png': path.resolve(__dirname, './src/assets/maxi8.png'),
        'figma:asset/whatsapp1.png': path.resolve(__dirname, './src/assets/whatsapp1.png'),
        'figma:asset/tv1.png': path.resolve(__dirname, './src/assets/tv1.png'),
        'figma:asset/maxi9.png': path.resolve(__dirname, './src/assets/maxi9.png'),
        'figma:asset/hisense9.png': path.resolve(__dirname, './src/assets/hisense9.png'),
        'figma:asset/lg10.png': path.resolve(__dirname, './src/assets/lg10.png'),
        'figma:asset/grand_pe_logo.png': path.resolve(__dirname, './src/assets/grand_pe_logo.png'),
        'figma:asset/hisense14.png': path.resolve(__dirname, './src/assets/hisense14.png'),
        'figma:asset/hisense12.png': path.resolve(__dirname, './src/assets/hisense12.png'),
        'figma:asset/power_solution1.png': path.resolve(__dirname, './src/assets/power_solution1.png'),
        'figma:asset/lg6.png': path.resolve(__dirname, './src/assets/lg6.png'),
        'figma:asset/maxi7.png': path.resolve(__dirname, './src/assets/maxi7.png'),
        'figma:asset/christmas_banner3.png': path.resolve(__dirname, './src/assets/christmas_banner3.png'),
        'figma:asset/christmas_banner2.png': path.resolve(__dirname, './src/assets/christmas_banner2.png'),
        'figma:asset/washing_machines.png': path.resolve(__dirname, './src/assets/washing_machines.png'),
        'figma:asset/lg9.png': path.resolve(__dirname, './src/assets/lg9.png'),
        'figma:asset/lg14.png': path.resolve(__dirname, './src/assets/lg14.png'),
        'figma:asset/growatt3.png': path.resolve(__dirname, './src/assets/growatt3.png'),
        'figma:asset/whatsapp3.png': path.resolve(__dirname, './src/assets/whatsapp3.png'),
        'figma:asset/lg13.png': path.resolve(__dirname, './src/assets/lg13.png'),
        'figma:asset/deye3.png': path.resolve(__dirname, './src/assets/deye3.png'),
        'figma:asset/hisense10.png': path.resolve(__dirname, './src/assets/hisense10.png'),
        'figma:asset/lg7.png': path.resolve(__dirname, './src/assets/lg7.png'),
        'figma:asset/lg11.png': path.resolve(__dirname, './src/assets/lg11.png'),
        'figma:asset/lg12.png': path.resolve(__dirname, './src/assets/lg12.png'),
        'figma:asset/huawei4.png': path.resolve(__dirname, './src/assets/huawei4.png'),
        'figma:asset/whatsapp2.png': path.resolve(__dirname, './src/assets/whatsapp2.png'),
        'figma:asset/furnitures1.png': path.resolve(__dirname, './src/assets/furnitures1.png'),
        'figma:asset/hisense13.png': path.resolve(__dirname, './src/assets/hisense13.png'),
        'embla-carousel-react@8.6.0': 'embla-carousel-react',
        'cmdk@1.1.1': 'cmdk',
        'class-variance-authority@0.7.1': 'class-variance-authority',
        '@radix-ui/react-tooltip@1.1.8': '@radix-ui/react-tooltip',
        '@radix-ui/react-toggle@1.1.2': '@radix-ui/react-toggle',
        '@radix-ui/react-toggle-group@1.1.2': '@radix-ui/react-toggle-group',
        '@radix-ui/react-tabs@1.1.3': '@radix-ui/react-tabs',
        '@radix-ui/react-switch@1.1.3': '@radix-ui/react-switch',
        '@radix-ui/react-slot@1.1.2': '@radix-ui/react-slot',
        '@radix-ui/react-slider@1.2.3': '@radix-ui/react-slider',
        '@radix-ui/react-separator@1.1.2': '@radix-ui/react-separator',
        '@radix-ui/react-select@2.1.6': '@radix-ui/react-select',
        '@radix-ui/react-scroll-area@1.2.3': '@radix-ui/react-scroll-area',
        '@radix-ui/react-radio-group@1.2.3': '@radix-ui/react-radio-group',
        '@radix-ui/react-progress@1.1.2': '@radix-ui/react-progress',
        '@radix-ui/react-popover@1.1.6': '@radix-ui/react-popover',
        '@radix-ui/react-navigation-menu@1.2.5': '@radix-ui/react-navigation-menu',
        '@radix-ui/react-menubar@1.1.6': '@radix-ui/react-menubar',
        '@radix-ui/react-label@2.1.2': '@radix-ui/react-label',
        '@radix-ui/react-hover-card@1.1.6': '@radix-ui/react-hover-card',
        '@radix-ui/react-dropdown-menu@2.1.6': '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-dialog@1.1.6': '@radix-ui/react-dialog',
        '@radix-ui/react-context-menu@2.2.6': '@radix-ui/react-context-menu',
        '@radix-ui/react-collapsible@1.1.3': '@radix-ui/react-collapsible',
        '@radix-ui/react-checkbox@1.1.4': '@radix-ui/react-checkbox',
        '@radix-ui/react-avatar@1.1.3': '@radix-ui/react-avatar',
        '@radix-ui/react-aspect-ratio@1.1.2': '@radix-ui/react-aspect-ratio',
        '@radix-ui/react-alert-dialog@1.1.6': '@radix-ui/react-alert-dialog',
        '@radix-ui/react-accordion@1.2.3': '@radix-ui/react-accordion',
        '@': path.resolve(__dirname, './src'),
      },
    },
    build: {
      target: 'esnext',
      outDir: 'build',
    },
    server: {
      port: 3000,
      open: true,
    },
  });